# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install lerna
        run: yarn global add lerna

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Unit test
        run: yarn test
